### ISSUE TITLE
Minecraft verison

### ISSUE THREAD

**Issue by ZoeS17** [yarrim/MobInhibitor#1]
Does this mod support verison, 1.8 of Minecraft for PC?

**Comment by yarrim** [comment]
I don't think so. I haven't begun playing 1.8, but I think there are some low level changes in the way Forge or native Minecraft mange resources. 
I'll take a look at what is required to port it.

**Comment by yarrim** [comment]
I'm skipping 1.8. Releasing 1.9.4 shortly and my code seems to work as-is for 1.10.2
