### ISSUE TITLE
1.12.2 maybe?

### ISSUE THREAD

**Issue by darthvader45** [yarrim/MobInhibitor#7]
Just wondering, is this mod dead, or do you have plans for newer versions of Minecraft?

**Comment by yarrim** [comment]
I never got around to updating Github, but published a 1.12.2 version on CurseForge:
https://minecraft.curseforge.com/projects/mobinhibitor

**Comment by darthvader45** [comment]
Thank you so much, this will greatly help me in securing my base (except for my dungeon, which shall be mob-infested for good reason).
